services:
  frontend:
    build: frontend
    ports:
     - 3200:3000
    networks:
      - mern
    env_file:
      - "frontend/.env"
  
  backend:
    build: backend
    ports:
     - 4200:4000
    networks:
     - mern
    depends_on:
      - mongo
    env_file:
      - "backend/.env"
    environment:
      - DB_URI=mongodb://mongo:27017/edsim
  
  mongo:
    image: mongo
    ports:
      - 27010:27017
    networks:
      - mern
    volumes:
      - /home/ubuntu/mongo-data:/data/db
  
networks:
  mern:
      driver: bridge

volumes:
  mongo-data:
    external: true